# Load R image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# Init runs during prebuild.
tasks:
  - name: Setup
    init: > # In YAML, > introduces spaces while | introduces newlines. XML libs required to build XML properly?
      Rscript -e '
        r = getOption("repos"); r["CRAN"]="http://cran.us.r-project.org"; options(repos=r);
        install.packes("renv"); renv::init();
        install.packages(c("remotes", "devtools"));
        remotes::install_github("ucl-medical-genomics/matt");
        devtools::install(".", dependencies="Suggests")
      '
    command: echo 'Run R setup'

# Settings
vscode:
  extensions:
    - Ikuyadeu.r

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

